# Generated by Django 3.0.5 on 2020-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200405_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_video',
            field=models.FileField(blank=True, default='', upload_to='templates', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=150),
        ),
    ]
