# Generated by Django 3.0.5 on 2020-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200406_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_video',
            field=models.FileField(default='', upload_to='templates/files/', verbose_name='Видео'),
        ),
    ]
