# Generated by Django 3.0.5 on 2020-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200409_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_now',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
